//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSIMedia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int Id { get; set; }
        public Nullable<decimal> A { get; set; }
        public Nullable<decimal> B { get; set; }
        public Nullable<decimal> C { get; set; }
        public Nullable<decimal> D { get; set; }
        public Nullable<decimal> E { get; set; }
        public Nullable<decimal> F { get; set; }
        public Nullable<decimal> G { get; set; }
        public Nullable<decimal> H { get; set; }
        public Nullable<decimal> J { get; set; }
    }
}
